# Generated by Django 2.2.5 on 2020-04-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price')),
                ('kind', models.CharField(choices=[('wood', 'Wood'), ('steel', 'Steel'), ('oil', 'Oil')], max_length=32, verbose_name='Kind')),
                ('user', models.ForeignKey(blank=True, help_text='User who regards to this example', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Import Example',
                'verbose_name_plural': 'Import Examples',
            },
        ),
    ]
